# Generated by Django 5.1.6 on 2025-10-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabase_agent_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageshistory',
            name='messages_json',
            field=models.TextField(),
        ),
    ]
