"""
Django settings for metabase_helpers project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import dotenv_values
import os

#check if .env file exists and load it, otherwise use environment variables

if os.path.exists(".env"):
    config = dotenv_values(".env")
else:
    config = os.environ


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.get("SECRET_KEY", None)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.get("DEBUG", "True").lower() == "true"


ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # registered apps
    "metabase_agent_helper",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "metabase_helpers.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "metabase_helpers.wsgi.application"
ASGI_APPLICATION = "metabase_helpers.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
if config.get("DB_DRIVER", "sqlite") != "pg":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config["DATABASE_NAME"],
            "USER": config["DATABASE_USER"],
            "PASSWORD": config["DATABASE_PASSWORD"],
            "HOST": config["DATABASE_HOST"],
            "PORT": config["DATABASE_PORT"],
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# API Keys and External Services
OPENAI_API_KEY = config.get("OPENAI_API_KEY", None)
DEEPSEEK_API_KEY = config.get("DEEPSEEK_API_KEY", None)
METABASE_API_KEY = config.get("METABASE_API_KEY", None)
METABASE_BASE_URL = config.get("METABASE_BASE_URL", None)
GROQ_API_KEY = config.get("GROQ_API_KEY", None)

#make sure logs directory exists
if not os.path.exists("logs"):
    os.makedirs("logs")

LOGGING = {
    "version": 1,
    "disable_exiting_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s :  %(levelname)s  :  %(name)s  :  %(message)s"
        },
        "file_logs": {
            "format": """{ "timestamp": %(asctime)s ,  "level" :%(levelname)s  , "module":%(name)s , "message":%(message)s }"""
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
        "file": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "formatter": "file_logs",
            "filename": "logs/logs.log",
            "when": "midnight",  # Rotate at midnight
            "interval": 1,  # Every 1 day
            "backupCount": 7,  # Keep 7 days of logs
        },
    },
    "loggers": {
        logging_app: {
            "level": "INFO",
            "handlers": ["console", "file"],
            "propagate": True,
        }
        for logging_app in INSTALLED_APPS + ["metabase_helpers", "django"]
    },
    "root": {
        "level": "INFO",
        "handles": ["console", "files"],
    },
}
