# Generated by Django 5.1.6 on 2025-10-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesHistory',
            fields=[
                ('primary_key', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('messages_json', models.JSONField()),
                ('conversation_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'MESSAGES HISTORY',
                'db_table': 'messages_history',
                'ordering': ['-primary_key'],
            },
        ),
    ]
